import { normalizeUserSkill, type UserSkill } from "./skill-library"

export const DEFAULT_BUILTIN_WRITING_SKILLS: UserSkill[] = [
  normalizeUserSkill({
    id: "builtin:chapter-connection",
    name: "章节承接",
    description: "检查上一章结尾、人物状态、未解决事件和必须承接的情绪。",
    kind: ["structure"],
    stages: ["planning"],
    modes: ["standard", "strict"],
    content: ["检查上一章结尾状态、人物位置与情绪、未解决事件。","确保本章承接前文的情绪基调和故事张力。","若发现重大承接缺口，在计划中标注。"].join("\\n"),
    source: "built-in",
  }),
  normalizeUserSkill({
    id: "builtin:next-chapter-plan",
    name: "下一章计划",
    description: "生成本章目标、冲突、人物、关键事件、伏笔安排和结尾钩子。",
    kind: ["planning"],
    stages: ["planning"],
    modes: ["standard", "strict"],
    content: ["生成包含以下要素的章节计划：","1. 本章目标","2. 核心冲突","3. 出场人物与动机","4. 关键事件顺序","5. 情绪曲线","6. 伏笔推进","7. 结尾钩子","8. 预计字数"].join("\\n"),
    source: "built-in",
  }),
  normalizeUserSkill({
    id: "builtin:mainline-check",
    name: "主线检查",
    description: "确认本章是否服务于故事主线。",
    kind: ["structure", "review"],
    stages: ["review", "planning"],
    modes: ["strict"],
    content: ["检查本章内容是否推进了以下至少一项：","1. 主角的核心目标","2. 主要冲突","3. 反派或压力来源","4. 阶段性转折","若完全不服务于主线，建议重新规划。"].join("\\n"),
    source: "built-in",
  }),
  normalizeUserSkill({
    id: "builtin:character-motivation",
    name: "人物动机",
    description: "检查人物行为是否合理。",
    kind: ["structure"],
    stages: ["planning", "review"],
    modes: ["standard", "strict"],
    content: ["对每个出场人物检查：","1. 他/她此刻想要什么？","2. 他/她害怕失去什么？","3. 行为是否符合前文设定？","4. 是否有独立于主角的行动逻辑？"].join("\\n"),
    source: "built-in",
  }),
  normalizeUserSkill({
    id: "builtin:conflict-escalation",
    name: "冲突升级",
    description: "保证本章有足够的矛盾、选择、代价和压力。",
    kind: ["structure"],
    stages: ["planning", "drafting"],
    modes: ["standard", "strict"],
    content: ["确保本章包含以下至少两项：","1. 人物之间的直接矛盾","2. 需要做出艰难选择","3. 承受代价或损失","4. 来自外部环境的压力升级","5. 内部心理斗争加剧"].join("\\n"),
    source: "built-in",
  }),
  normalizeUserSkill({
    id: "builtin:foreshadowing-management",
    name: "伏笔管理",
    description: "判断哪些伏笔该推进、隐藏、回收或暂缓。",
    kind: ["structure", "review"],
    stages: ["planning", "review"],
    modes: ["strict"],
    content: ["对现有伏笔逐一判断：","1. 哪些本章适合推进","2. 哪些太久未处理","3. 哪些不应提前揭示","4. 哪些已到回收时机"].join("\\n"),
    source: "built-in",
  }),
  normalizeUserSkill({
    id: "builtin:rhythm-check",
    name: "节奏检查",
    description: "避免章节过慢、过散或中段塌陷。",
    kind: ["review"],
    stages: ["review"],
    modes: ["strict"],
    content: ["检查本章节奏：","1. 开头是否太慢？","2. 是否有过多无关场景堆叠？","3. 中段是否塌陷或重复？","4. 高潮是否足够支撑？","5. 结尾是否有力？"].join("\\n"),
    source: "built-in",
  }),
  normalizeUserSkill({
    id: "builtin:ending-hook",
    name: "结尾钩子",
    description: "提供悬念、反转、危机升级等结尾方案。",
    kind: ["structure", "planning"],
    stages: ["planning", "drafting"],
    modes: ["strict"],
    content: ["建议本章结尾选择以下至少一种方式：","1. 强悬念结尾","2. 反转结尾","3. 危机升级结尾","4. 情绪余韵结尾","5. 人物关系变化结尾"].join("\\n"),
    source: "built-in",
  }),
  normalizeUserSkill({
    id: "builtin:plot-self-check",
    name: "剧情自检",
    description: "正文生成后检查剧情质量。",
    kind: ["review"],
    stages: ["review"],
    modes: ["standard", "strict"],
    content: ["正文生成后逐一检查：","1. 剧情是否自然承接上一章","2. 主线是否推进","3. 人物动机是否合理","4. 本章冲突是否足够","5. 伏笔是否推进","6. 节奏是否合适","7. 是否符合 soul.md 风格"].join("\\n"),
    source: "built-in",
  }),
  normalizeUserSkill({
    id: "builtin:output-protocol",
    name: "正文输出协议",
    description: "保证回复只输出章节正文，不混入过程信息。",
    kind: ["output"],
    stages: ["output"],
    modes: ["fast", "standard", "strict"],
    content: ["最终输出要求：","1. 只输出章节标题和正文","2. 不输出分析过程","3. 不输出 Skill 使用说明","4. 不输出检查结果","5. 不输出任何元信息"].join("\\n"),
    source: "built-in",
  }),
]

export function getBuiltinSkillIds(): Set<string> {
  return new Set(DEFAULT_BUILTIN_WRITING_SKILLS.map((s) => s.id))
}
